name: durable_outbox
description: A reliable offline queue library with guaranteed delivery for Flutter/Dart applications.
version: 0.1.0
homepage: https://github.com/atlet99/durable_outbox
repository: https://github.com/atlet99/durable_outbox
issue_tracker: https://github.com/atlet99/durable_outbox/issues
documentation: https://github.com/atlet99/durable_outbox/blob/main/README.md
topics:
  - durable
  - offline
  - queue

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.5.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

